import{state}from'./state.js';import{MUNICIPALITIES}from'./config.js';import{$,escapeHtml,number,normalizePoblacion,today,icons}from'./utils.js';let refresh=()=>{};export const configureTable=f=>refresh=f;
export function renderTable(){const body=$('table-body');body.innerHTML='';const start=(state.page-1)*state.pageSize,rows=state.filtered.slice(start,start+state.pageSize);if(!rows.length)body.innerHTML='<tr><td colspan="9" class="p-6 text-slate-400">No se encontraron registros.</td></tr>';for(const r of rows){const i=state.raw.indexOf(r),cmd=number(r.CMD),cmes=number(r.CMES),badge=r.Observaciones?`<span title="${escapeHtml(r.Observaciones)}" class="px-2 py-1 rounded bg-amber-100 text-amber-800">Incidencia</span>`:'<span class="px-2 py-1 rounded bg-emerald-100 text-emerald-800">Normal</span>';const tr=document.createElement('tr');tr.className='hover:bg-sky-50 border-b';tr.innerHTML=`<td class="p-2">${escapeHtml(r.Fecha)}</td><td>${escapeHtml(r.CodigoDispositivo)}</td><td>${escapeHtml(r.NombreDispositivo)}</td><td>${escapeHtml(normalizePoblacion(r.Poblacion))}</td><td>${escapeHtml(r.CodigoSenal)}</td><td>${cmd===null?'#N/D':cmd.toLocaleString('es-ES')}</td><td>${cmes===null?'#N/D':cmes.toLocaleString('es-ES')}</td><td>${badge}</td><td><button data-edit="${i}" class="p-1 text-sky-600">Editar</button><button data-delete="${i}" class="p-1 text-rose-600">Eliminar</button></td>`;body.append(tr)}const max=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));$('pagination-info').textContent=`Mostrando ${rows.length?start+1:0}-${Math.min(start+state.pageSize,state.filtered.length)} de ${state.filtered.length}`;$('page-num').textContent=`Página ${state.page} de ${max}`;$('btn-prev-page').disabled=state.page===1;$('btn-next-page').disabled=state.page===max;icons()}
export function tableClick(e){const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openEdit(+edit.dataset.edit);if(del)deleteRecord(+del.dataset.delete)}
function municipalities(){return MUNICIPALITIES.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('')}
export function openAdd(){$('modal-title').textContent='Añadir registro hidráulico';$('edit-record-index').value=-1;$('record-poblacion').innerHTML=municipalities();$('record-form').reset();$('record-fecha').value=today();$('modal-record').classList.remove('hidden')}
function openEdit(i){const r=state.raw[i];$('modal-title').textContent='Editar registro hidráulico';$('edit-record-index').value=i;$('record-poblacion').innerHTML=municipalities();for(const[id,v]of Object.entries({'record-fecha':r.Fecha,'record-poblacion':normalizePoblacion(r.Poblacion),'record-cod-disp':r.CodigoDispositivo,'record-nom-disp':r.NombreDispositivo,'record-cod-senal':r.CodigoSenal,'record-cmd':number(r.CMD)??'','record-cmes':number(r.CMES)??'','record-obs':r.Observaciones||''}))$(id).value=v;$('modal-record').classList.remove('hidden')}
export const closeModal=()=>$('modal-record').classList.add('hidden');
export function saveRecord(e){e.preventDefault();const i=+$('edit-record-index').value,code=$('record-cod-disp').value.trim(),r={Fecha:$('record-fecha').value,CodigoDispositivo:code,NombreDispositivo:$('record-nom-disp').value.trim()||code,Poblacion:$('record-poblacion').value,CodigoSenal:$('record-cod-senal').value.trim()||`SIG-${code}`,CMD:$('record-cmd').value===''?'#N/D':+$('record-cmd').value,CMES:$('record-cmes').value===''?'#N/D':+$('record-cmes').value,Observaciones:$('record-obs').value.trim()||null};i>=0?state.raw[i]=r:state.raw.unshift(r);closeModal();refresh()}
function deleteRecord(i){if(confirm('¿Eliminar este registro?')){state.raw.splice(i,1);refresh()}}
export function sortBy(c){state.sortDir=state.sortCol===c&&state.sortDir==='desc'?'asc':'desc';state.sortCol=c;refresh()}
export function prev(){if(state.page>1){state.page--;renderTable()}}export function next(){if(state.page<Math.ceil(state.filtered.length/state.pageSize)){state.page++;renderTable()}}